# Generated by Django 5.1.1 on 2024-10-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0004_comment_parent_alter_reply_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
