# Generated by Django 5.1.1 on 2024-10-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0005_remove_comment_date_delete_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
