# Generated by Django 5.1.1 on 2024-10-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
