# Generated by Django 5.1.1 on 2024-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0008_alter_post_image_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog-post-image'),
        ),
    ]
