# Generated by Django 5.1.1 on 2024-10-07 09:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0010_alter_post_image_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=cloudinary.models.CloudinaryField(default='profile_images/blank-profile-picture.png', max_length=255, verbose_name='image'),
        ),
    ]
