# Generated by Django 5.1.1 on 2024-10-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0011_alter_post_image_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.URLField(default='profile_images/blank-profile-picture.png', verbose_name='image'),
        ),
    ]
