# Generated by Django 5.1.1 on 2024-10-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0012_alter_post_image_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog-post-images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='profile_images/blank-profile-picture.png', upload_to='profile_images/'),
        ),
    ]
